production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  database: nolan_anagram_development
  pool: 5
  host: localhost
  username: nolanfrazier
  password:

test:
  adapter: postgresql
  database: nolan_anagram_test
  pool: 5
  host: localhost
  username: nolanfrazier
  password:
